### ISSUE TITLE
如何定义代码块的背景颜色呢？

### ISSUE THREAD

**Issue by Yak0xff** [monniya/hexo-theme-new-vno#1]

**Comment by monniya** [comment]
请修改/themes/new-vno/source/css/vno.styl这个文件，比如短代码是code {background: #e8f2fb;}控制

**Comment by monniya** [comment]
请修改/themes/new-vno/source/css/vno.styl这个文件，比如短代码是code {background: #e8f2fb;}控制

**Comment by Yak0xff** [comment]
OK.  3Q
