### ISSUE TITLE
线下正常，线上异常报错

### ISSUE THREAD

**Issue by 286810** [monniya/hexo-theme-new-vno#11]
Mixed Content: The page at 'https://286810.github.io/' was loaded over HTTPS, but requested an insecure script 'http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

jQuery 被阻止加载了？怎么解决？谢谢！

**Comment by monniya** [comment]
额，貌似需要你自己上https
