### ISSUE TITLE
头像、标题都显示在最左边怎么回事儿

### ISSUE THREAD

**Issue by NanayaHaruki** [monniya/hexo-theme-new-vno#12]
而且点击博客也没反应..

**Comment by NanayaHaruki** [comment]
http://cdn.bootcss.com/jquery/2.1.4/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
是这东西的问题，layout/layout.ejs里http得改成https

**Comment by monniya** [comment]
好的，没搞全站https，有空折腾下
