### ISSUE TITLE
副标题(介绍自我)变为两条下划线。

### ISSUE THREAD

**Issue by mrpsweet** [monniya/hexo-theme-new-vno#14]
副标题(介绍自我)变为两条下划线。按照作者的.md提示做的不知道是怎么回事。

**Comment by NanayaHaruki** [comment]
description 没填吧

**Comment by mrpsweet** [comment]
黄金屋和时光机，是如何做的，新建一个html？

**Comment by monniya** [comment]
@mrpsweet 教程我写了，你看下：http://monniya.com/2016/01/31/create-book-list/
