### ISSUE TITLE
能否告知你博客的图床是哪里的吗？

### ISSUE THREAD

**Issue by xuekepei** [monniya/hexo-theme-new-vno#17]
我看到 cdn.monniya.com 指向了一个日本的服务器

**Comment by monniya** [comment]
图床是自建的 VPS，欢迎用这个链接购买 https://www.vultr.com/?ref=6871895/

**Comment by zhangferry** [comment]
你好，当我使用这个主题进入博客时，显示的下面效果，并没有在右侧显示文章列表。这是怎么回事呢
![image](https://cloud.githubusercontent.com/assets/13702445/21092710/06d45ac0-c089-11e6-8210-2417ec1b23d1.png)

**Comment by Menci** [comment]
可能是旧主题的 `/js/main.js` 缓存了，清空缓存刷新一下试试

**Comment by monniya** [comment]
是之前的主题未兼容https部署，layout/layout.ejs内的js文件改下成https即可

**Comment by zhangferry** [comment]
@monniya 谢谢回复呀。但是我已经换了另一个主题了。。

**Comment by monniya** [comment]
好的，比较忙（都是借口），终于把https给上了😂
