### ISSUE TITLE
请教一下主题中黄金屋、时光机的功能是如何实现的

### ISSUE THREAD

**Issue by VeiZhang** [monniya/hexo-theme-new-vno#19]
RT

**Comment by monniya** [comment]
详见这篇文章：https://monniya.com/2016/01/31/create-book-list/

**Comment by VeiZhang** [comment]
好滴，谢谢

**Comment by VeiZhang** [comment]
不好意思额。参考你的教程，出现一个问题：点击图片不能跳转，点击书籍标题可以跳转链接，参考你的源码样式，还是点击图片不能跳转，出现的是一个提示信息？？？

**Comment by monniya** [comment]
很简单啊，因为图片没有包在a链接里面呀，我是故意这么弄的，你可以把a链接层级提出一层就好了，修改下源码

**Comment by VeiZhang** [comment]
ok，谢谢
