### ISSUE TITLE
可以自行添加email进去，以及一些小小问题

### ISSUE THREAD

**Issue by Lucien-Zhang** [monniya/hexo-theme-new-vno#22]
这个文件下包含了email的代码，所以如果写进全局的config，应该会出现一个邮箱的图标，我只是发现了，自己没有尝试...

```
themes\new-vno\layout\_partial\social.ejs
```

想问一下：
1. 如果想在这个主题上修改的话，是要fork一个分支在自己账户上，修改完后合并到master吗？代码小白什么都不懂.......
2. 我想添加一个categories，弄个nav 按钮，跳转到categories页面，或者弄个tag归档页面。因为觉得这个博客一旦文章发布得多的话要找其实挺麻烦的....
3. 想知道照片的边框是靠css美化的，还是图床限定的？自己在html页面看css代码看的有点绕...

**Comment by monniya** [comment]
1、不用的哈，你在自己本地修改就好了，或者推送到自己到git，当然有bug可以向我提。
2、我是就用tag分类的
3、css
