### ISSUE TITLE
fatal: repository 'https://github.com/monniya/hexo-theme-vno.git/' not found

### ISSUE THREAD

**Issue by czn6** [monniya/hexo-theme-new-vno#3]
fatal: repository 'https://github.com/monniya/hexo-theme-vno.git/' not found

安装不了 似乎地址有错误

**Comment by monniya** [comment]
https://github.com/monniya/hexo-theme-new-vno.git   是这个地址，少了个new

**Comment by monniya** [comment]
请问你是哪里复制的这个地址？

**Comment by czn6** [comment]
@monniya 你 的readme 里的~

**Comment by monniya** [comment]
看到了，sorry，改好了

**Comment by czn6** [comment]
谢谢
