### ISSUE TITLE
使用此主题 列表乱码 但是文章内容是正常的 

### ISSUE THREAD

**Issue by superbobogithub** [monniya/hexo-theme-new-vno#4]
求解，能给解决下嘛

**Comment by onevcat** [comment]
看起来是渲染首页的时候的截取的 helper 编码的问题吧- -...我不是很懂 hexo，可以试试看更新一下 hexo？或者选择和 @monniya 一样的生成版本..

因为和主题本身其实无关，更多的可能是模板的问题，所以 https://github.com/onevcat/vno/issues/24 这个 issue 我先关了。
