### ISSUE TITLE
hexo g 执行失败，原因：【description：】字段为必选字段。

### ISSUE THREAD

**Issue by leopardpan** [monniya/hexo-theme-new-vno#6]
hexo g 执行失败。
环境：`hexo init` 新建博客 --> clone new-vno 主题 --> 修改主题后直接执行 `hexo g` 命令。
现象：提示执行失败，具体error就不贴了，很好复现。
原因：`new-vno/layout/_partial/head.ejs` 文件里有用到 博客根目录下的 `description` 字段。
解决方法： blog/_config.yml 文件 `description：` 必须写个字段，如 `description：test`。
期望：作者能把 `description:` 变成可选字段。
修改保存后就执行 `hexo g` 就能成功了。

另外附带一个小问题：头像 avatar.jpg 的形状问题。
描述：avatar.jpg 是根据图片形状来设置的，如 avatar.jpg 是长方形，那么 博客头像就是椭圆形了。  
不确定这是不是博客主题是不是就是这么设计的。

-- thanks

**Comment by monniya** [comment]
你好：因为首页样式需要，description的确是必填的，不然首页排版会变，已经改成可选（其实在description赋值前加个判断即可），至于头像，我只是限制了宽度，高度等比例，所以你上传长方形的会变成椭圆，若要强制圆形，你可以上传方图，或在样式中把高度也限定

**Comment by leopardpan** [comment]
OK，thanks!
