### ISSUE TITLE
代码块总是莫名其妙的多出几行。

### ISSUE THREAD

**Issue by halftrue** [monniya/hexo-theme-new-vno#8]
例如：

http://xuxiaokang.github.io/2016/03/29/LeetCode-114-Flatten-Binary-Tree-to-Linked-List/

http://xuxiaokang.github.io/2016/05/15/LeetCode-59-Maximum-Subarray/

总是会多出3-5行。

**Comment by sud0why** [comment]
因为你代码段里面有空行，主题的CSS不完善，所以我是自己改了CSS引入了别的代码高亮的js和css

**Comment by Ir1d** [comment]
@sud0why 方便说下是怎么改的嘛……谢谢
