### ISSUE TITLE
两个评论框的问题

### ISSUE THREAD

**Issue by sud0why** [monniya/hexo-theme-new-vno#9]
感觉应该是原主题的问题。page页面会有两个评论框。
就是page.ejs有一个评论框，layout有一个评论框，然后去掉page.ejs里面
<% if (page.comment || theme.page_comment) { %>
<%- partial('_partial/comments',{}) %>
<% } %>
这段才剩下的一个。我不确定是我改主题的问题还是这部分确实渲染出来两个。。。没看hexo主题的开发。。

**Comment by monniya** [comment]
好的，我检查看看
